### ISSUE TITLE
✨ [Feat] CRUD 중 CR 구현

### ISSUE THREAD

**Issue by suminiee** [SMUMC-7th/7th_Spring#34]
## 📝 개요
- Chapter 3. CRUD 중 CR 구현

## ✔️ To-Do
- [ ] Article CR 구현
- [ ] Reply CR 구현
- [ ] createdAt, updatedAt 사용 가능하도록 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성
