### ISSUE TITLE
✨ [Feat] CRUD 중 CR 구현

### ISSUE THREAD

**Issue by JH627** [SMUMC-7th/7th_Spring#37]
## 📝 개요
- CRUD 중 CR 구현

## ✔️ To-Do
- [x] Article 클래스 구현
- [x] createdAt, updatedAt 적용되도록 수정 
- [x] 게시글 생성, 게시글 전체 조회, 게시글 하나 조회 API 구현 
- [x] Reply CR 구현 
------------
- [x] Article에 `@OneToMany` 구현
- [x] createdAt과 updatedAt을 이용하여 클래스를 구현 후 모든 엔티티에 extends
- [x] 컨트롤러의 응답을 엔티티가 아닌 DTO로 대체하기
- [x] Article 관련 ErrorCode, Exception 구현
- [x] ArticleCommandServiceImpl 내부의 Builder 패턴 사용하여 객체를 만드는 부분을 ArticleConverter라는 클래스를 사용하거나 응답 DTO에서 반환하도록 하기

## 👀 ETC
- 3주차 워크북 참고
