### ISSUE TITLE
✨ [Feat] CRUD 중 CR

### ISSUE THREAD

**Issue by chaerish** [SMUMC-7th/7th_Spring#49]
## 📝 개요
-  article 클래스 구현 및 CRUD의 CR 적용

## ✔️ To-Do
- [ ]  article 클래스 구현
- [ ] createdAt, updatedAt 적용되도록 수정
- [ ] 게시글 생성, 게시글 전체 조회, 게시글 하나 조회 API 구현
- [ ]  Reply CR 구현
- [ ] ArticleCommandServiceImpl 내부의 Builder 패턴 사용하여 객체를 만드는 부분을 ArticleConverter라는 클래스를 사용하거나 응답 DTO에서 반환하도록 하기

## 👀 ETC
- 참고자료 등 기타 내용 작성
